### ISSUE TITLE
Labels not working for scale_*_met_d()

### ISSUE THREAD

**Issue by lbozhilova** [BlakeRMills/MetBrewer#18]
Hi Blake,

I love this newest version of MetBrewer so much! I've been introducing colleagues to it very enthusiastically. Unfortunately I just spotted that I can't set custom legend labels in `scale_*_met_d()` using `labels` in the usual way. Here's an example.

```
data(iris)

iris_labs <- paste("I.", levels(iris$Species))
names(iris_labs) <- levels(iris$Species)

# Species labels changed successfully
ggplot(iris, aes(x = Petal.Length, y = Petal.Width, colour = Species)) +
  geom_point() +
  scale_colour_discrete(labels = iris_labs)

# Species labels not changed
ggplot(iris, aes(x = Petal.Length, y = Petal.Width, colour = Species)) +
  geom_point() +
  scale_colour_met_d("Renoir", labels = iris_labs)
```

Not a huge issue, but worth keeping in mind for future versions!

Cheers,
Lyuba

**Comment by db369** [comment]
I can confirm this. I can't seem to pass any arguments on to discrete_scale. I haven't tried all, but those I have tried - including labels - doesn't work.  The workaround is using scale_*_manual(values = met.brewer(pal), ....) method.
