### ISSUE TITLE
How to set pallet in ggplot2

### ISSUE THREAD

**Issue by selesnow** [BlakeRMills/MetBrewer#2]
Hello, thanks for MetBrewer!

Could you show how i can apply palettes from it to ggplot2 plots?

For example, next code it works, 
```r
library(ggplot2)
library(MetBrewer)

ggplot(data=iris, 
       aes(x=Sepal.Length, 
           y=Petal.Length, 
           color=Species))+
  ggtitle("Iris")+
  geom_point()+
  scale_color_manual(values = MetBrewer::MetPalettes$Cross[[1]][1:3])
```

but i think there should be a more graceful way to apply the palette.

**Comment by BlakeRMills** [comment]
Hi, 

Thanks for checking out MetBrewer. 

I would not recommend using the MetPalettes list. That only exists to feed into the met.brewer() function which allows you to generate the colors. For the example above, the code would look like this


```
library(ggplot2)
library(MetBrewer)

ggplot(data=iris, 
       aes(x=Sepal.Length, 
           y=Petal.Length, 
           color=Species))+
  ggtitle("Iris")+
  geom_point()+
  scale_color_manual(values = MetBrewer::met.brewer("Cross", 3)
```

You can also scroll to the bottom of the main page [here](https://github.com/BlakeRMills/MetBrewer) to see some ways to use the function. I'd also recommend looking at the documentation for the function by running this is R
```
library(MetBrewer)
?met.brewer()
``` 

Let me know if that answers your question.

Best,
Blake

**Comment by selesnow** [comment]
Thanks!
